### ISSUE TITLE
En este caso la recursividad te juega en contra

### ISSUE THREAD

**Issue by MMartinez2001** [OvidioSantoro/beginners-javascript#5]
https://github.com/OvidioSantoro/beginners-javascript/blob/e83e724e4a732d54bcaca29dc79ec2ff79958ca8/index.js#L47

Visualizando tu código:

```js
function letterCounter(letterCode, array){

    let filtered = filter(array);
    let letter = String.fromCharCode(letterCode);
    let iterations = 0;

    for (let i = 0; i < filtered.length; i++){
        for (let j = 0; j < filtered[i].length; j++){
            // Convierte las letras a lowercase para hacer case-insensitive el resultado.
            if (filtered[i][j].toLowerCase() === letter){
                iterations++
            }
        }
    }

    let result = `The letter "${letter}" is repeated ${iterations} times.\n`

    if (letterCode < 122){
        return result + letterCounter(letterCode + 1, array);
    } else{
        return result;
    }
}

// Cuenta cuantas repeticiones de cada letra hay en el array dado
function lettersInArray(array){
    // Letra en ASCII, para recorrer recursivamente el alfabeto en la función. 97 = "a"
    return letterCounter(97, array);
}
```

Voy a comenzar por definirte que es un coste algorítmico. El coste es la cantidad de recursos que un algoritmo necesita para ejecutarse, ya sea tiempo de reloj, CPU o RAM.

Si te das cuenta estas usando un conjunto de dos for-s y encima recursivo, este algoritmo tiene un coste **elevadísimo**. En este caso haber utilizado recursividad en un problema que no era necesario te está generando una cuota de rendimiento muy baja, la recursividad en JS es peligrosa ya que existe un concepto llamado **Call Stack** (investígalo) que puede hacer que tu programa se vaya al carajo :) 

Está función si tienes que repetirla desde el principio, tienes dos opciones para contar las letras, ya sea crear un objeto simple como un diccionario:

```js
let response = {}
```
y ahí colocar todos los valores o ya sea usando un array multidimensional (matriz) para almacenar los datos. En este caso tu has utilizado dos funciones, una que ejecuta el código y la otra que la llama, para que el ejercicio sea correcto y optimo solo debes crear una función.

**Comment by OvidioSantoro** [comment]
Reconstruida esa parte del ejercicio en una sola función. Nuevamente, pensé que no podía utilizar objetos y por eso le di más vueltas de las necesarias. La nueva función es:

```javascript
// Contea las repeticiones de una letra, comenzando por la letra indicada y se repite recursivamente hasta llegar a la "z"
function letterCounter(array){

    let filtered = filter(array);
    let iterations = {};

    for (let i = 0; i < filtered.length; i++){
        for (let j = 0; j < filtered[i].length; j++){
            // Convierte las letras a lowercase para hacer case-insensitive el resultado.
            let letter = filtered[i][j].toLowerCase();

            // Comprueba que el elemento sea una letra y no un símbolo (@) o un número
            if (letter.charCodeAt(0) >= 97 && letter.charCodeAt(0) <= 122){
                if (!iterations[letter]){
                    iterations[letter] = 1;
                } else{
                    iterations[letter]+= 1; 
                }
            }
        }
    }

    return iterations
}
```
