### ISSUE TITLE
Reto personal.

### ISSUE THREAD

**Issue by MMartinez2001** [OvidioSantoro/beginners-javascript#7]
https://github.com/OvidioSantoro/beginners-javascript/blob/e83e724e4a732d54bcaca29dc79ec2ff79958ca8/index.js#L107

Me gusta mucho este código, es exactamente el correcto, pero tengo que decirte que no atiende a los principios de la programación funcional. Ese código podría segmentarse en dos funciones para hacerlo aún más optimo y reutilizar código en el futuro, de cara a un proyecto grande.

Quiero que encuentres la manera de separarlo en dos funciones que sean optimas.

**Comment by OvidioSantoro** [comment]
Dividida la función original en dos funciones: una función **reverse** que devuelve una string con los valores del revés y una función **reverseArray** que llama a la función **reverse** para cada string que compone el array.

**Comment by MMartinez2001** [comment]
Recibido, mandamelo todo pro Breathcode!!!
