### ISSUE TITLE
Fallo de concepto y errores algorítmicos 

### ISSUE THREAD

**Issue by whitehatdevv** [OvidioSantoro/beginners-javascript#9]
https://github.com/OvidioSantoro/beginners-javascript/blob/2366ea07c00be1af29c3ebd1a1e65c5d1a0e66ed/index.js#L50

Si observamos tu código: 

```js 

// Contea las repeticiones de una letra, comenzando por la letra indicada y se repite recursivamente hasta llegar a la "z"
function letterCounter(array) {

    let filtered = filter(array);
    let iterations = {};

    for (let i = 0; i < filtered.length; i++) {
        for (let j = 0; j < filtered[i].length; j++) {
            // Convierte las letras a lowercase para hacer case-insensitive el resultado.
            let letter = filtered[i][j].toLowerCase();

            // Comprueba que el elemento sea una letra y no un símbolo (@) o un número
            if (letter.charCodeAt(0) >= 97 && letter.charCodeAt(0) <= 122) {
                if (!iterations[letter]) {
                    iterations[letter] = 1;
                } else {
                    iterations[letter] += 1;
                }
            }
        }
    }

    return iterations
}

```

Si observas el comentario superior, indicas que esta función es recursiva y **no lo es**. Una función recursiva es una función que se llama así misma dentro de ella para continuar un proceso. 
Pero no se queda solo aquí, estás comprobando el código ASCII de los caracteres, algo totalmente innecesario en este ejercicio, tienes que pensar una solución que no mire el código ASCII, por que a ti te da igual si es un @ o es cualquier elemento, una vez limpia tu tienes que contar todo lo que quede, sin importar si es un símbolo. Por ende una solución correcta sería la siguiente: 

```js

// contar el numero de repeticiones de letra en un array
function countLetterMatches(array) {

    let response = {};

    // limpiamos el array
    const cleanData = cleanArray(array);

    // recorremos el array
    for (let item of cleanData) {

        // recorremos cada letra dal item
        for (let letter of item) {

            // comprobamos si existe
            if (response.hasOwnProperty(letter.toLowerCase())) {
                // aumentamos el contador de repeticioines
                response[letter.toLowerCase()]++;
            } else {
                // creamos una nueva propiedad
                response[letter.toLowerCase()] = 1;
            }

        }

    }

    return response;

}

```

`reponse` está siendo usado como diccionario no como objeto. Cualquier cosa coméntame, pero debes cambiarlo. No vale copiarse de esta, además debes tener en cuenta que la P y p son la misma letra.

**Comment by OvidioSantoro** [comment]
- Cambiada la descripción de la función letterCounter(), la descripción previo correspondía a un función obsoleta eliminada del código.
- Alterado el funcionamiento de la función letterCounter(), ahora acepta símbolos además de letras.
- Modificado el README con los cambios realizados.
